const NonProgrammingProjectInfo = [
    {
        previewImg:'',
        projectName: '',
        timeline: '',
        subject: '',
        myRoles: '',
        tools: '',
        overview: '',
        problem: '',
        solution: '',
        finalProduct: '',
        keyTakeaways: '',
        process: '',
    },
    {
        previewImg:'',
        projectName: '',
        timeline: '',
        subject: '',
        myRoles: '',
        tools: '',
        overview: '',
        problem: '',
        solution: '',
        finalProduct: '',
        keyTakeaways: '',
        process: '',
    },
    {
        previewImg:'',
        projectName: '',
        timeline: '',
        subject: '',
        myRoles: '',
        tools: '',
        overview: '',
        problem: '',
        solution: '',
        finalProduct: '',
        keyTakeaways: '',
        process: '',
    },
]